# Generated by Django 5.1.4 on 2025-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('course_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_paid', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=1000, null=True)),
                ('subscribers', models.IntegerField(blank=True, null=True)),
                ('num_lectures', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('All Levels', 'All Levels'), ('Intermediate Level', 'Intermediate level'), ('Beginner Level', 'Beginner level'), ('Expert Level', 'Expert level')], max_length=100, null=True)),
                ('content_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, choices=[('Business Finance', 'Business Finance'), ('Graphic Design', 'Graphic Design'), ('Musical Instruments', 'Musical Instruments'), ('Web Development', 'Web Development')], max_length=500, null=True)),
                ('published_timestamp', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
